[phases.build]
nixPkgs = ["postgresql", "python311"]

[phases.setup]
nixPkgs = ["postgresql", "python311"]

[phases.install]
cmds = ["pip install --upgrade pip && pip install -r requirements.txt"]

[start]
cmd = "sh -c 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT'"
